bootstrap.servers=kafka1:29092,kafka2:29092,kafka3:29092
client.id=perf-consumer-durability
group.id=perf-consumer-durability
auto.offset.reset=earliest
enable.auto.commit=false
isolation.level=read_committed
