bootstrap.servers=kafka1:29092,kafka2:29092,kafka3:29092
client.id=perf-consumer-latency
group.id=perf-consumer-latency
auto.offset.reset=earliest
fetch.min.bytes=1
fetch.max.wait.ms=100
max.poll.records=500
