bootstrap.servers=kafka1:29092,kafka2:29092,kafka3:29092
client.id=perf-producer-latency
acks=1
linger.ms=0
batch.size=1024
compression.type=none
max.in.flight.requests.per.connection=1
buffer.memory=33554432
