bootstrap.servers=kafka1:29092,kafka2:29092,kafka3:29092
client.id=perf-consumer-availability
group.id=perf-consumer-availability
auto.offset.reset=earliest
session.timeout.ms=10000
heartbeat.interval.ms=3000
max.poll.interval.ms=300000
